@WebApplication1_HostAddress = http://localhost:5177

GET {{WebApplication1_HostAddress}}/todos/
Accept: application/json

###

GET {{WebApplication1_HostAddress}}/todos/1
Accept: application/json

###
